[package]
name = "hyper-native-tls"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]

[dependencies]
antidote = "1.0"
native-tls = "0.1"
hyper = { version = "0.9", default-features = false }

[dev-dependencies]
openssl = "0.9"
hyper-openssl = "0.1"
